site_name: Echo
theme: journal
theme_dir: echo
copyright: '&copy; 2015 LabStack'
repo_url: https://github.com/labstack/echo
google_analytics: ['UA-51208124-3', 'auto']
pages:
  - Home: index.md
  - Guide: guide.md
  - Recipes:
    - File Upload: recipes/file-upload.md
    - Streaming File Upload: recipes/streaming-file-upload.md
    - Streaming Response: recipes/streaming-response.md
    - WebSocket: recipes/websocket.md
    - Subdomains: recipes/subdomains.md
    - JWT Authentication: recipes/jwt-authentication.md
    - Graceful Shutdown: recipes/graceful-shutdown.md
extra:
  site_title: Echo, a fast and unfancy micro web framework for Golang.
